services:
  web:
    container_name: dockercloud-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
